### PR TITLE
Add a changelog

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by rictic** [comment]
The plugin lives in the client folder, and the language server lives in the server folder. The client depends on the server. In the very short term future we're gonna move the language server out to polymer-editor-service, but this was the folder layout that was recommended by the language server example code that I started from.

**Comment by usergenic** [comment]
If the `CHANGELOG.md` is eventually moving to repo root then LGTM.

**Comment by rictic** [comment]
Thanks for the review!

**Comment by rictic** [comment]
Changelog.md moved to toplevel as promised in #39.

**Pull request closed without merging**
